language: node_js
node_js:
    - "6"
    - "7"
    - "8"
    - "9"
    - "10"
    - "11"

script:
    - "npm run test-sa"
    - "npm run test-cc"
after_script:
    - "npm run test-cc-post"
cache:
    node: true
